spring:
  datasource:
    url: jdbc:mysql://localhost:3306/voters?createDatabaseIfNotExist=TRUE&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: mysql
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
    hibernate:
      ddl-auto: create

